apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: dissol-co-uk-tls
spec:
  secretName: dissol-co-uk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dissol.co.uk
  dnsNames:
    - dissol.co.uk
    - www.dissol.co.uk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - dissol.co.uk
          - www.dissol.co.uk